version: '2'

services:
  electric-service:
    image: electric-service
    ports:
      - "127.0.0.1:8080:8080"
    depends_on:
      - redis
    network_mode: "host"
  redis:
    image: redis
    ports:
      - "127.0.0.1:6379:6379"
    network_mode: "host"
